#pragma once

// From glfw3.h
#define HM_MOUSE_BUTTON_1 0
#define HM_MOUSE_BUTTON_2 1
#define HM_MOUSE_BUTTON_3 2
#define HM_MOUSE_BUTTON_4 3
#define HM_MOUSE_BUTTON_5 4
#define HM_MOUSE_BUTTON_6 5
#define HM_MOUSE_BUTTON_7 6
#define HM_MOUSE_BUTTON_8 7
#define HM_MOUSE_BUTTON_LAST HM_MOUSE_BUTTON_8
#define HM_MOUSE_BUTTON_LEFT HM_MOUSE_BUTTON_1
#define HM_MOUSE_BUTTON_RIGHT HM_MOUSE_BUTTON_2
#define HM_MOUSE_BUTTON_MIDDLE HM_MOUSE_BUTTON_3